{{- if eq .Values.spire.enabled true }}
# ClusterSPIFFEID for apiserver workload
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  {{- if ne .Values.spire.className "none" }}
  className: {{ .Values.spire.className | default (printf "%s-spire" .Release.Namespace) }}
  {{- end }}
  {{- if .Values.spire.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.spire.namespaceSelector | nindent 4 }}
  {{- end }}
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - {{ include "chart.name" . }}
  workloadSelectorTemplates:
    - k8s:pod-image:{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
    - k8s:sa:{{ include "chart.serviceAccountName" . }}
  spiffeIDTemplate: {{ "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}" }}
  autoPopulateDNSNames: true
  {{- if .Values.spire.dnsNameTemplates }}
  dnsNameTemplates:
    {{- toYaml .Values.spire.dnsNameTemplates | nindent 4 }}
  {{- end }}
  {{- if .Values.spire.federation }}
  federatesWith:
  {{ range .Values.spire.federation }}
    - {{ .trustDomain }}
  {{ end }}
  {{- end }}
{{- end }}
