// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agntcy/dir/runtime/v1/discovery_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DiscoveryService_GetWorkload_FullMethodName   = "/agntcy.dir.runtime.v1.DiscoveryService/GetWorkload"
	DiscoveryService_ListWorkloads_FullMethodName = "/agntcy.dir.runtime.v1.DiscoveryService/ListWorkloads"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DiscoveryService defines the gRPC service for discovering workloads.
// The service itself does not actually perform discovery, but rather queries the
// underlying store for existing workloads.
// It supports filtering workloads based on provided criteria.
type DiscoveryServiceClient interface {
	// Get a workload by its identifier.
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*Workload, error)
	// List all workloads based on filters.
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (DiscoveryService_ListWorkloadsClient, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*Workload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workload)
	err := c.cc.Invoke(ctx, DiscoveryService_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (DiscoveryService_ListWorkloadsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DiscoveryService_ServiceDesc.Streams[0], DiscoveryService_ListWorkloads_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryServiceListWorkloadsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiscoveryService_ListWorkloadsClient interface {
	Recv() (*Workload, error)
	grpc.ClientStream
}

type discoveryServiceListWorkloadsClient struct {
	grpc.ClientStream
}

func (x *discoveryServiceListWorkloadsClient) Recv() (*Workload, error) {
	m := new(Workload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations should embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
//
// DiscoveryService defines the gRPC service for discovering workloads.
// The service itself does not actually perform discovery, but rather queries the
// underlying store for existing workloads.
// It supports filtering workloads based on provided criteria.
type DiscoveryServiceServer interface {
	// Get a workload by its identifier.
	GetWorkload(context.Context, *GetWorkloadRequest) (*Workload, error)
	// List all workloads based on filters.
	ListWorkloads(*ListWorkloadsRequest, DiscoveryService_ListWorkloadsServer) error
}

// UnimplementedDiscoveryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) GetWorkload(context.Context, *GetWorkloadRequest) (*Workload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedDiscoveryServiceServer) ListWorkloads(*ListWorkloadsRequest, DiscoveryService_ListWorkloadsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_ListWorkloads_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListWorkloadsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServiceServer).ListWorkloads(m, &discoveryServiceListWorkloadsServer{ServerStream: stream})
}

type DiscoveryService_ListWorkloadsServer interface {
	Send(*Workload) error
	grpc.ServerStream
}

type discoveryServiceListWorkloadsServer struct {
	grpc.ServerStream
}

func (x *discoveryServiceListWorkloadsServer) Send(m *Workload) error {
	return x.ServerStream.SendMsg(m)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agntcy.dir.runtime.v1.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkload",
			Handler:    _DiscoveryService_GetWorkload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListWorkloads",
			Handler:       _DiscoveryService_ListWorkloads_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agntcy/dir/runtime/v1/discovery_service.proto",
}
